# Generated by Django 4.2.1 on 2023-07-09 11:01

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WeatherData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lat", models.DecimalField(decimal_places=6, max_digits=9)),
                ("lon", models.DecimalField(decimal_places=6, max_digits=9)),
                ("detailing_type", models.CharField(max_length=20)),
                ("forecast_data", models.JSONField()),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
